bundler_args: --without production
before_script: bundle exec rails db:create db:migrate
cache: bundler
language: ruby
rvm:
  - 2.5.1
sript:
  - bundle exec rspec
sudo: required
dist: precise
branch:
  only:
    - master
