bundler_args: --without production
before_script: bundle exec rails db:create db:migrate
cache: bundler
language: ruby
rvm:
  - 2.3.0
sript:
  - bundle exec rspec
sudo: false
dist: xenial
branch:
  only:
    - master
